### PR TITLE
Export safes to binary.

### PR DESCRIPTION
**Pull request by chriseth**

### CODE REVIEW

**Comment by almereyda** [comment]
@chriseth I have changed the target branch of your PR from `main` to `dev`, and take this in, as there are no merge conflicts (merge early and merge often).

Same rationale as in https://github.com/CirclesUBI/pathfinder2/pull/18#issuecomment-1487167182 applies.

**Comment by almereyda** [comment]
OP-89

**Comment by chriseth** [comment]
Ok! I'm not sure about the state of this PR but it looks kind of ok.

**Comment by almereyda** [comment]
Thank you for having a look. We'll be able to inspect appearing regressions in subsequent issues then.

**Pull request merged**
